"""add scheduled games for strength of schedule

Revision ID: 4b5fe6898121
Revises: 8998cd8a5ad0
Create Date: 2026-09-03 19:20:51.310525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders JSONB column variants as
# ``postgresql.JSONB(astext_type=Text())`` with a bare ``Text``, so the name has
# to be in scope for the generated module to import.
from sqlalchemy import Text  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '4b5fe6898121'
down_revision: Union[str, Sequence[str], None] = '8998cd8a5ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_game_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=8), nullable=False),
    sa.Column('home_team', sa.String(length=8), nullable=False),
    sa.Column('away_team', sa.String(length=8), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_games')),
    sa.UniqueConstraint('provider_game_id', 'source', name='uq_scheduled_game_per_provider')
    )
    op.create_index(op.f('ix_scheduled_games_away_team'), 'scheduled_games', ['away_team'], unique=False)
    op.create_index(op.f('ix_scheduled_games_home_team'), 'scheduled_games', ['home_team'], unique=False)
    op.create_index(op.f('ix_scheduled_games_observed_at'), 'scheduled_games', ['observed_at'], unique=False)
    op.create_index(op.f('ix_scheduled_games_provider_game_id'), 'scheduled_games', ['provider_game_id'], unique=False)
    op.create_index(op.f('ix_scheduled_games_season'), 'scheduled_games', ['season'], unique=False)
    op.create_index('ix_scheduled_games_season_week', 'scheduled_games', ['season', 'week'], unique=False)
    op.create_index(op.f('ix_scheduled_games_source'), 'scheduled_games', ['source'], unique=False)
    op.create_index(op.f('ix_scheduled_games_week'), 'scheduled_games', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_games_week'), table_name='scheduled_games')
    op.drop_index(op.f('ix_scheduled_games_source'), table_name='scheduled_games')
    op.drop_index('ix_scheduled_games_season_week', table_name='scheduled_games')
    op.drop_index(op.f('ix_scheduled_games_season'), table_name='scheduled_games')
    op.drop_index(op.f('ix_scheduled_games_provider_game_id'), table_name='scheduled_games')
    op.drop_index(op.f('ix_scheduled_games_observed_at'), table_name='scheduled_games')
    op.drop_index(op.f('ix_scheduled_games_home_team'), table_name='scheduled_games')
    op.drop_index(op.f('ix_scheduled_games_away_team'), table_name='scheduled_games')
    op.drop_table('scheduled_games')
    # ### end Alembic commands ###
