"""add rookie season and coaches

Revision ID: 6e2662c1d6da
Revises: 4b5fe6898121
Create Date: 2026-09-03 20:22:32.114115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders JSONB column variants as
# ``postgresql.JSONB(astext_type=Text())`` with a bare ``Text``, so the name has
# to be in scope for the generated module to import.
from sqlalchemy import Text  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '6e2662c1d6da'
down_revision: Union[str, Sequence[str], None] = '4b5fe6898121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('rookie_season', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('draft_year', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('draft_round', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('draft_pick', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_players_rookie_season'), 'players', ['rookie_season'], unique=False)
    op.add_column('scheduled_games', sa.Column('home_coach', sa.String(length=64), nullable=True))
    op.add_column('scheduled_games', sa.Column('away_coach', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_games', 'away_coach')
    op.drop_column('scheduled_games', 'home_coach')
    op.drop_index(op.f('ix_players_rookie_season'), table_name='players')
    op.drop_column('players', 'draft_pick')
    op.drop_column('players', 'draft_round')
    op.drop_column('players', 'draft_year')
    op.drop_column('players', 'rookie_season')
    # ### end Alembic commands ###
