"""initial schema

Revision ID: 8998cd8a5ad0
Revises: 
Create Date: 2026-08-22 11:38:52.462800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders JSONB column variants as
# ``postgresql.JSONB(astext_type=Text())`` with a bare ``Text``, so the name has
# to be in scope for the generated module to import.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8998cd8a5ad0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=96), nullable=False),
    sa.Column('requested_resource', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('rows_unresolved_identity', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=48), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('source_checksum', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_ingestion_runs'))
    )
    with op.batch_alter_table('data_ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_ingestion_runs_dataset'), ['dataset'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_ingestion_runs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_ingestion_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_ingestion_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_ingestion_provider_dataset_started', ['provider', 'dataset', 'started_at'], unique=False)

    op.create_table('data_quality_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('check_name', sa.String(length=96), nullable=False),
    sa.Column('dataset', sa.String(length=96), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('failing_row_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sample_failures', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_results'))
    )
    with op.batch_alter_table('data_quality_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_results_check_name'), ['check_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_results_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_results_ingestion_run_id'), ['ingestion_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_results_passed'), ['passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_results_severity'), ['severity'], unique=False)

    op.create_table('fantasy_leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_league_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('scoring_format', sa.String(length=16), nullable=False),
    sa.Column('roster_positions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scoring_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('raw_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fantasy_leagues')),
    sa.UniqueConstraint('provider_league_id', 'source', name='uq_league_per_provider')
    )
    with op.batch_alter_table('fantasy_leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fantasy_leagues_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_leagues_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_leagues_provider_league_id'), ['provider_league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_leagues_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_leagues_source'), ['source'], unique=False)

    op.create_table('player_identity_conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sleeper_id', sa.String(length=64), nullable=True),
    sa.Column('observed_name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('candidate_ids', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_identity_conflicts')),
    sa.UniqueConstraint('sleeper_id', 'reason', name='uq_conflict_per_player_reason')
    )
    with op.batch_alter_table('player_identity_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_identity_conflicts_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_identity_conflicts_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_identity_conflicts_resolved'), ['resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_identity_conflicts_sleeper_id'), ['sleeper_id'], unique=False)

    op.create_table('players',
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('weight_pounds', sa.Integer(), nullable=True),
    sa.Column('college', sa.String(length=96), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('identity_method', sa.String(length=32), nullable=False),
    sa.Column('identity_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('player_uuid', name=op.f('pk_players'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('ix_players_active_position', ['is_active', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_popularity_rank'), ['popularity_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_position'), ['position'], unique=False)
        batch_op.create_index('ix_players_position_team', ['position', 'team'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team'), ['team'], unique=False)

    op.create_table('provider_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=96), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('cursor', sa.String(length=128), nullable=True),
    sa.Column('next_attempt_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_sync_state')),
    sa.UniqueConstraint('provider', 'dataset', name='uq_sync_state_per_dataset')
    )
    with op.batch_alter_table('provider_sync_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_sync_state_last_success_at'), ['last_success_at'], unique=False)

    op.create_table('seasons',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(length=16), nullable=True),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('season', name=op.f('pk_seasons'))
    )
    op.create_table('teams',
    sa.Column('abbreviation', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('conference', sa.String(length=8), nullable=True),
    sa.Column('division', sa.String(length=16), nullable=True),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('abbreviation', name=op.f('pk_teams'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_season'), ['season'], unique=False)

    op.create_table('adp_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('scoring_format', sa.String(length=16), nullable=False),
    sa.Column('league_size', sa.Integer(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=False),
    sa.Column('adp_stdev', sa.Float(), nullable=True),
    sa.Column('min_pick', sa.Float(), nullable=True),
    sa.Column('max_pick', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_adp_snapshots_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adp_snapshots')),
    sa.UniqueConstraint('player_uuid', 'season', 'scoring_format', 'source', 'snapshot_date', name='uq_adp_snapshot')
    )
    with op.batch_alter_table('adp_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_adp_season_format_date', ['season', 'scoring_format', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_adp_snapshots_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_adp_snapshots_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_adp_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_adp_snapshots_source'), ['source'], unique=False)

    op.create_table('availability_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=False),
    sa.Column('horizon_weeks', sa.Integer(), nullable=False),
    sa.Column('probability_unavailable', sa.Float(), nullable=False),
    sa.Column('calibrated', sa.Boolean(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_availability_predictions_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_predictions')),
    sa.UniqueConstraint('player_uuid', 'model_version', 'season', 'week', 'horizon_weeks', name='uq_availability_prediction')
    )
    with op.batch_alter_table('availability_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_predictions_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_predictions_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_predictions_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_predictions_source'), ['source'], unique=False)

    op.create_table('current_player_health',
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('designation', sa.String(length=24), nullable=False),
    sa.Column('raw_injury_status', sa.String(length=64), nullable=True),
    sa.Column('body_region', sa.String(length=32), nullable=True),
    sa.Column('raw_body_part', sa.Text(), nullable=True),
    sa.Column('injury_notes', sa.Text(), nullable=True),
    sa.Column('injury_start_date', sa.Date(), nullable=True),
    sa.Column('practice_status', sa.String(length=16), nullable=True),
    sa.Column('practice_trajectory', sa.String(length=24), nullable=True),
    sa.Column('depth_chart_position', sa.String(length=16), nullable=True),
    sa.Column('depth_chart_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_current_player_health_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_uuid', name=op.f('pk_current_player_health'))
    )
    with op.batch_alter_table('current_player_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_current_player_health_designation'), ['designation'], unique=False)
        batch_op.create_index(batch_op.f('ix_current_player_health_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_current_player_health_source'), ['source'], unique=False)

    op.create_table('depth_chart_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('depth_position', sa.String(length=16), nullable=True),
    sa.Column('depth_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_depth_chart_snapshots_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depth_chart_snapshots')),
    sa.UniqueConstraint('player_uuid', 'season', 'week', 'source', name='uq_depth_chart_observation')
    )
    with op.batch_alter_table('depth_chart_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depth_chart_snapshots_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_depth_chart_snapshots_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_depth_chart_snapshots_source'), ['source'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('provider_draft_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('draft_type', sa.String(length=16), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('user_draft_slot', sa.Integer(), nullable=True),
    sa.Column('slot_to_roster_id', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pick_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_leagues.id'], name=op.f('fk_drafts_league_id_fantasy_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts')),
    sa.UniqueConstraint('provider_draft_id', 'source', name='uq_draft_per_provider')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_last_polled_at'), ['last_polled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_provider_draft_id'), ['provider_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_status'), ['status'], unique=False)

    op.create_table('fantasy_projections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('scoring_format', sa.String(length=16), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('projected_points_low', sa.Float(), nullable=True),
    sa.Column('projected_points_high', sa.Float(), nullable=True),
    sa.Column('projected_games', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_fantasy_projections_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fantasy_projections')),
    sa.UniqueConstraint('player_uuid', 'season', 'week', 'scoring_format', 'source', name='uq_projection_observation')
    )
    with op.batch_alter_table('fantasy_projections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fantasy_projections_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_projections_scoring_format'), ['scoring_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_projections_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_projections_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_projections_week'), ['week'], unique=False)
        batch_op.create_index('ix_projection_season_format', ['season', 'scoring_format'], unique=False)

    op.create_table('fantasy_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('scoring_format', sa.String(length=16), nullable=False),
    sa.Column('league_size', sa.Integer(), nullable=False),
    sa.Column('roster_signature', sa.String(length=64), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=False),
    sa.Column('position_rank', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('value_over_replacement', sa.Float(), nullable=True),
    sa.Column('health_risk', sa.Float(), nullable=True),
    sa.Column('adp_value', sa.Float(), nullable=True),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_fantasy_rankings_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fantasy_rankings')),
    sa.UniqueConstraint('player_uuid', 'season', 'roster_signature', 'computed_at', name='uq_ranking_snapshot')
    )
    with op.batch_alter_table('fantasy_rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fantasy_rankings_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_rankings_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_rankings_roster_signature'), ['roster_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_rankings_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_fantasy_rankings_source'), ['source'], unique=False)
        batch_op.create_index('ix_ranking_lookup', ['season', 'roster_signature', 'overall_rank'], unique=False)

    op.create_table('fantasy_rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('owner_provider_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=96), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['fantasy_leagues.id'], name=op.f('fk_fantasy_rosters_league_id_fantasy_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fantasy_rosters')),
    sa.UniqueConstraint('league_id', 'roster_id', name='uq_roster_per_league')
    )
    with op.batch_alter_table('fantasy_rosters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fantasy_rosters_league_id'), ['league_id'], unique=False)

    op.create_table('health_score_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('availability_estimate', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('practice_trajectory', sa.String(length=24), nullable=True),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_health_score_snapshots_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_score_snapshots')),
    sa.UniqueConstraint('player_uuid', 'model_version', 'computed_at', name='uq_health_snapshot')
    )
    with op.batch_alter_table('health_score_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_health_player_computed', ['player_uuid', 'computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_score_snapshots_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_score_snapshots_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_score_snapshots_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_score_snapshots_risk_band'), ['risk_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_score_snapshots_source'), ['source'], unique=False)

    op.create_table('injury_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=8), nullable=True),
    sa.Column('body_region', sa.String(length=32), nullable=False),
    sa.Column('secondary_region', sa.String(length=32), nullable=True),
    sa.Column('raw_primary_injury', sa.Text(), nullable=True),
    sa.Column('raw_secondary_injury', sa.Text(), nullable=True),
    sa.Column('designation', sa.String(length=24), nullable=False),
    sa.Column('raw_report_status', sa.String(length=64), nullable=True),
    sa.Column('games_missed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_injury_events_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injury_events')),
    sa.UniqueConstraint('player_uuid', 'season', 'week', 'source', name='uq_injury_event_observation')
    )
    with op.batch_alter_table('injury_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injury_events_body_region'), ['body_region'], unique=False)
        batch_op.create_index(batch_op.f('ix_injury_events_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_injury_events_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_injury_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_injury_events_week'), ['week'], unique=False)
        batch_op.create_index('ix_injury_player_season', ['player_uuid', 'season'], unique=False)
        batch_op.create_index('ix_injury_region_season', ['body_region', 'season'], unique=False)

    op.create_table('player_external_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('system', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_player_external_ids_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_external_ids')),
    sa.UniqueConstraint('player_uuid', 'system', name='uq_one_id_per_system_per_player'),
    sa.UniqueConstraint('system', 'external_id', name='uq_external_id_per_system')
    )
    with op.batch_alter_table('player_external_ids', schema=None) as batch_op:
        batch_op.create_index('ix_player_external_lookup', ['system', 'external_id'], unique=False)

    op.create_table('player_weekly_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(length=8), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('opponent', sa.String(length=8), nullable=True),
    sa.Column('carries', sa.Float(), nullable=True),
    sa.Column('targets', sa.Float(), nullable=True),
    sa.Column('receptions', sa.Float(), nullable=True),
    sa.Column('pass_attempts', sa.Float(), nullable=True),
    sa.Column('sacks_taken', sa.Float(), nullable=True),
    sa.Column('passing_yards', sa.Float(), nullable=True),
    sa.Column('passing_tds', sa.Float(), nullable=True),
    sa.Column('interceptions', sa.Float(), nullable=True),
    sa.Column('rushing_yards', sa.Float(), nullable=True),
    sa.Column('rushing_tds', sa.Float(), nullable=True),
    sa.Column('receiving_yards', sa.Float(), nullable=True),
    sa.Column('receiving_tds', sa.Float(), nullable=True),
    sa.Column('fumbles_lost', sa.Float(), nullable=True),
    sa.Column('fantasy_points_standard', sa.Float(), nullable=True),
    sa.Column('fantasy_points_half_ppr', sa.Float(), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_player_weekly_stats_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_weekly_stats')),
    sa.UniqueConstraint('player_uuid', 'season', 'week', 'source', name='uq_weekly_stat_observation')
    )
    with op.batch_alter_table('player_weekly_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_weekly_stats_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_weekly_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_weekly_stats_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_weekly_stats_week'), ['week'], unique=False)
        batch_op.create_index('ix_weekly_player_season', ['player_uuid', 'season'], unique=False)

    op.create_table('practice_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_status', sa.String(length=96), nullable=True),
    sa.Column('body_region', sa.String(length=32), nullable=True),
    sa.Column('raw_injury', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_practice_reports_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_reports')),
    sa.UniqueConstraint('player_uuid', 'season', 'week', 'source', name='uq_practice_observation')
    )
    with op.batch_alter_table('practice_reports', schema=None) as batch_op:
        batch_op.create_index('ix_practice_player_season_week', ['player_uuid', 'season', 'week'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_reports_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_reports_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_reports_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_reports_week'), ['week'], unique=False)

    op.create_table('snap_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('offense_snaps', sa.Integer(), nullable=True),
    sa.Column('offense_snap_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_snap_counts_player_uuid_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snap_counts')),
    sa.UniqueConstraint('player_uuid', 'season', 'week', 'source', name='uq_snap_count_observation')
    )
    with op.batch_alter_table('snap_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snap_counts_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_snap_counts_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_snap_counts_source'), ['source'], unique=False)

    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('pick_no', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('draft_slot', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=True),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('provider_player_id', sa.String(length=64), nullable=True),
    sa.Column('picked_by', sa.String(length=64), nullable=True),
    sa.Column('is_keeper', sa.Boolean(), nullable=False),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_draft_picks_draft_id_drafts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_draft_picks_player_uuid_players'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_picks')),
    sa.UniqueConstraint('draft_id', 'pick_no', name='uq_pick_number_per_draft'),
    sa.UniqueConstraint('draft_id', 'player_uuid', name='uq_player_once_per_draft')
    )
    with op.batch_alter_table('draft_picks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_picks_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_picks_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_picks_source'), ['source'], unique=False)
        batch_op.create_index('ix_pick_draft_order', ['draft_id', 'pick_no'], unique=False)

    op.create_table('draft_recommendation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('pick_no', sa.Integer(), nullable=False),
    sa.Column('user_draft_slot', sa.Integer(), nullable=True),
    sa.Column('best_player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('best_overall_score', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computation_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_draft_recommendation_snapshots_draft_id_drafts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_recommendation_snapshots')),
    sa.UniqueConstraint('draft_id', 'pick_no', name='uq_recommendation_per_pick')
    )
    with op.batch_alter_table('draft_recommendation_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_recommendation_snapshots_draft_id'), ['draft_id'], unique=False)

    op.create_table('draft_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('draft_slot', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=True),
    sa.Column('provider_user_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=96), nullable=True),
    sa.Column('team_name', sa.String(length=96), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_draft_slots_draft_id_drafts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_slots')),
    sa.UniqueConstraint('draft_id', 'draft_slot', name='uq_slot_per_draft')
    )
    with op.batch_alter_table('draft_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_slots_draft_id'), ['draft_id'], unique=False)

    op.create_table('roster_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roster_pk', sa.Integer(), nullable=False),
    sa.Column('player_uuid', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('lineup_slot', sa.String(length=16), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_uuid'], ['players.player_uuid'], name=op.f('fk_roster_players_player_uuid_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roster_pk'], ['fantasy_rosters.id'], name=op.f('fk_roster_players_roster_pk_fantasy_rosters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roster_players')),
    sa.UniqueConstraint('roster_pk', 'player_uuid', name='uq_player_once_per_roster')
    )
    with op.batch_alter_table('roster_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roster_players_roster_pk'), ['roster_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roster_players_roster_pk'))

    op.drop_table('roster_players')
    with op.batch_alter_table('draft_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_slots_draft_id'))

    op.drop_table('draft_slots')
    with op.batch_alter_table('draft_recommendation_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_recommendation_snapshots_draft_id'))

    op.drop_table('draft_recommendation_snapshots')
    with op.batch_alter_table('draft_picks', schema=None) as batch_op:
        batch_op.drop_index('ix_pick_draft_order')
        batch_op.drop_index(batch_op.f('ix_draft_picks_source'))
        batch_op.drop_index(batch_op.f('ix_draft_picks_observed_at'))
        batch_op.drop_index(batch_op.f('ix_draft_picks_draft_id'))

    op.drop_table('draft_picks')
    with op.batch_alter_table('snap_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snap_counts_source'))
        batch_op.drop_index(batch_op.f('ix_snap_counts_season'))
        batch_op.drop_index(batch_op.f('ix_snap_counts_observed_at'))

    op.drop_table('snap_counts')
    with op.batch_alter_table('practice_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_reports_week'))
        batch_op.drop_index(batch_op.f('ix_practice_reports_source'))
        batch_op.drop_index(batch_op.f('ix_practice_reports_season'))
        batch_op.drop_index(batch_op.f('ix_practice_reports_observed_at'))
        batch_op.drop_index('ix_practice_player_season_week')

    op.drop_table('practice_reports')
    with op.batch_alter_table('player_weekly_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_weekly_player_season')
        batch_op.drop_index(batch_op.f('ix_player_weekly_stats_week'))
        batch_op.drop_index(batch_op.f('ix_player_weekly_stats_source'))
        batch_op.drop_index(batch_op.f('ix_player_weekly_stats_season'))
        batch_op.drop_index(batch_op.f('ix_player_weekly_stats_observed_at'))

    op.drop_table('player_weekly_stats')
    with op.batch_alter_table('player_external_ids', schema=None) as batch_op:
        batch_op.drop_index('ix_player_external_lookup')

    op.drop_table('player_external_ids')
    with op.batch_alter_table('injury_events', schema=None) as batch_op:
        batch_op.drop_index('ix_injury_region_season')
        batch_op.drop_index('ix_injury_player_season')
        batch_op.drop_index(batch_op.f('ix_injury_events_week'))
        batch_op.drop_index(batch_op.f('ix_injury_events_source'))
        batch_op.drop_index(batch_op.f('ix_injury_events_season'))
        batch_op.drop_index(batch_op.f('ix_injury_events_observed_at'))
        batch_op.drop_index(batch_op.f('ix_injury_events_body_region'))

    op.drop_table('injury_events')
    with op.batch_alter_table('health_score_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_score_snapshots_source'))
        batch_op.drop_index(batch_op.f('ix_health_score_snapshots_risk_band'))
        batch_op.drop_index(batch_op.f('ix_health_score_snapshots_observed_at'))
        batch_op.drop_index(batch_op.f('ix_health_score_snapshots_model_version'))
        batch_op.drop_index(batch_op.f('ix_health_score_snapshots_computed_at'))
        batch_op.drop_index('ix_health_player_computed')

    op.drop_table('health_score_snapshots')
    with op.batch_alter_table('fantasy_rosters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fantasy_rosters_league_id'))

    op.drop_table('fantasy_rosters')
    with op.batch_alter_table('fantasy_rankings', schema=None) as batch_op:
        batch_op.drop_index('ix_ranking_lookup')
        batch_op.drop_index(batch_op.f('ix_fantasy_rankings_source'))
        batch_op.drop_index(batch_op.f('ix_fantasy_rankings_season'))
        batch_op.drop_index(batch_op.f('ix_fantasy_rankings_roster_signature'))
        batch_op.drop_index(batch_op.f('ix_fantasy_rankings_observed_at'))
        batch_op.drop_index(batch_op.f('ix_fantasy_rankings_computed_at'))

    op.drop_table('fantasy_rankings')
    with op.batch_alter_table('fantasy_projections', schema=None) as batch_op:
        batch_op.drop_index('ix_projection_season_format')
        batch_op.drop_index(batch_op.f('ix_fantasy_projections_week'))
        batch_op.drop_index(batch_op.f('ix_fantasy_projections_source'))
        batch_op.drop_index(batch_op.f('ix_fantasy_projections_season'))
        batch_op.drop_index(batch_op.f('ix_fantasy_projections_scoring_format'))
        batch_op.drop_index(batch_op.f('ix_fantasy_projections_observed_at'))

    op.drop_table('fantasy_projections')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_drafts_source'))
        batch_op.drop_index(batch_op.f('ix_drafts_provider_draft_id'))
        batch_op.drop_index(batch_op.f('ix_drafts_observed_at'))
        batch_op.drop_index(batch_op.f('ix_drafts_league_id'))
        batch_op.drop_index(batch_op.f('ix_drafts_last_polled_at'))

    op.drop_table('drafts')
    with op.batch_alter_table('depth_chart_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depth_chart_snapshots_source'))
        batch_op.drop_index(batch_op.f('ix_depth_chart_snapshots_season'))
        batch_op.drop_index(batch_op.f('ix_depth_chart_snapshots_observed_at'))

    op.drop_table('depth_chart_snapshots')
    with op.batch_alter_table('current_player_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_current_player_health_source'))
        batch_op.drop_index(batch_op.f('ix_current_player_health_observed_at'))
        batch_op.drop_index(batch_op.f('ix_current_player_health_designation'))

    op.drop_table('current_player_health')
    with op.batch_alter_table('availability_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_predictions_source'))
        batch_op.drop_index(batch_op.f('ix_availability_predictions_season'))
        batch_op.drop_index(batch_op.f('ix_availability_predictions_observed_at'))
        batch_op.drop_index(batch_op.f('ix_availability_predictions_model_version'))

    op.drop_table('availability_predictions')
    with op.batch_alter_table('adp_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adp_snapshots_source'))
        batch_op.drop_index(batch_op.f('ix_adp_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_adp_snapshots_season'))
        batch_op.drop_index(batch_op.f('ix_adp_snapshots_observed_at'))
        batch_op.drop_index('ix_adp_season_format_date')

    op.drop_table('adp_snapshots')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_season'))

    op.drop_table('teams')
    op.drop_table('seasons')
    with op.batch_alter_table('provider_sync_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_sync_state_last_success_at'))

    op.drop_table('provider_sync_state')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team'))
        batch_op.drop_index(batch_op.f('ix_players_source'))
        batch_op.drop_index('ix_players_position_team')
        batch_op.drop_index(batch_op.f('ix_players_position'))
        batch_op.drop_index(batch_op.f('ix_players_popularity_rank'))
        batch_op.drop_index(batch_op.f('ix_players_observed_at'))
        batch_op.drop_index(batch_op.f('ix_players_normalized_name'))
        batch_op.drop_index('ix_players_active_position')

    op.drop_table('players')
    with op.batch_alter_table('player_identity_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_identity_conflicts_sleeper_id'))
        batch_op.drop_index(batch_op.f('ix_player_identity_conflicts_resolved'))
        batch_op.drop_index(batch_op.f('ix_player_identity_conflicts_reason'))
        batch_op.drop_index(batch_op.f('ix_player_identity_conflicts_normalized_name'))

    op.drop_table('player_identity_conflicts')
    with op.batch_alter_table('fantasy_leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fantasy_leagues_source'))
        batch_op.drop_index(batch_op.f('ix_fantasy_leagues_season'))
        batch_op.drop_index(batch_op.f('ix_fantasy_leagues_provider_league_id'))
        batch_op.drop_index(batch_op.f('ix_fantasy_leagues_observed_at'))
        batch_op.drop_index(batch_op.f('ix_fantasy_leagues_is_demo'))

    op.drop_table('fantasy_leagues')
    with op.batch_alter_table('data_quality_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_results_severity'))
        batch_op.drop_index(batch_op.f('ix_data_quality_results_passed'))
        batch_op.drop_index(batch_op.f('ix_data_quality_results_ingestion_run_id'))
        batch_op.drop_index(batch_op.f('ix_data_quality_results_checked_at'))
        batch_op.drop_index(batch_op.f('ix_data_quality_results_check_name'))

    op.drop_table('data_quality_results')
    with op.batch_alter_table('data_ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_ingestion_provider_dataset_started')
        batch_op.drop_index(batch_op.f('ix_data_ingestion_runs_status'))
        batch_op.drop_index(batch_op.f('ix_data_ingestion_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_data_ingestion_runs_provider'))
        batch_op.drop_index(batch_op.f('ix_data_ingestion_runs_dataset'))

    op.drop_table('data_ingestion_runs')
    # ### end Alembic commands ###
