"""Value objects for the health engine's inputs and outputs."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date

from fhe.core.types import (
    BodyRegion,
    InjuryDesignation,
    Position,
    PracticeStatus,
    PracticeTrajectory,
)


@dataclass(frozen=True, slots=True)
class InjuryHistoryEvent:
    """One historical injury observation, already normalised.

    Args:
        season: NFL season the event was reported in.
        week: Week within the season, when known.
        region: Normalised body region.
        raw_descriptor: The provider's original text, never discarded.
        designation: Game status attached to the report, if any.
        games_missed: Games the player was unavailable for because of this event,
            when it can be established from the data. ``None`` means unknown -
            which is deliberately different from zero.
    """

    season: int
    region: BodyRegion
    raw_descriptor: str
    week: int | None = None
    designation: InjuryDesignation = InjuryDesignation.UNKNOWN
    games_missed: int | None = None


@dataclass(frozen=True, slots=True)
class WorkloadSummary:
    """Recent usage, used both as an exposure signal and a durability signal."""

    season: int | None = None
    games_played: int | None = None
    snaps_per_game: float | None = None
    carries_per_game: float | None = None
    targets_per_game: float | None = None

    @property
    def touches_per_game(self) -> float | None:
        """Carries plus targets, the exposure measure that matters for skill players."""
        if self.carries_per_game is None and self.targets_per_game is None:
            return None
        return (self.carries_per_game or 0.0) + (self.targets_per_game or 0.0)


@dataclass(frozen=True, slots=True)
class HealthInputs:
    """Everything the heuristic scorer reads.

    Every field is optional except identity, because real player rows are
    incomplete and the scorer must degrade honestly rather than assume defaults.
    Data completeness is reported back through
    :attr:`HealthAssessment.confidence`.
    """

    player_uuid: str
    position: Position
    as_of: date

    designation: InjuryDesignation = InjuryDesignation.ACTIVE
    current_injury_region: BodyRegion | None = None
    injury_start_date: date | None = None

    practice_statuses: tuple[PracticeStatus, ...] = field(default=())
    injury_history: tuple[InjuryHistoryEvent, ...] = field(default=())

    age: float | None = None
    years_experience: int | None = None
    workload: WorkloadSummary | None = None

    # Season the assessment is being made for; drives injury-recency decay.
    current_season: int | None = None


@dataclass(frozen=True, slots=True)
class RiskComponent:
    """One explainable contribution to the overall risk score.

    Args:
        name: Stable machine-readable key, e.g. ``"current_designation"``.
        label: Human-readable label for the UI.
        points: Signed contribution in risk points. Positive increases risk.
        detail: Deterministic sentence explaining the contribution. Never
            generated by a language model.
    """

    name: str
    label: str
    points: float
    detail: str


@dataclass(frozen=True, slots=True)
class HealthAssessment:
    """The scorer's output.

    Args:
        player_uuid: Internal player identifier.
        risk_score: 0-100, where higher means more availability risk.
        raw_score: The unclamped sum of ``components``. Exposing this keeps the
            displayed arithmetic honest when clamping is in play - a clean
            profile can sum below zero, and a catastrophic one above 100.
        availability_estimate: Estimated share of remaining games the player is
            available for, in ``[0, 1]``.
        confidence: 0-1 measure of how much of the input signal was actually
            present. A high-risk score at low confidence should be presented as
            uncertain, not authoritative.
        components: The signed contributions that sum to the raw score.
        practice_trajectory: Direction of recent practice participation.
        model_version: Identifier of the scoring logic that produced this.
        limitations: Plain-language caveats surfaced in the UI.
    """

    player_uuid: str
    risk_score: float
    raw_score: float
    availability_estimate: float
    confidence: float
    components: tuple[RiskComponent, ...]
    practice_trajectory: PracticeTrajectory
    model_version: str
    limitations: tuple[str, ...] = field(default=())

    @property
    def risk_band(self) -> str:
        """Coarse band used for non-colour-only encoding in the UI."""
        if self.risk_score >= 70:
            return "SEVERE"
        if self.risk_score >= 45:
            return "ELEVATED"
        if self.risk_score >= 25:
            return "MODERATE"
        return "LOW"
